version: '3.4'

services:
  dockercore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  corefirst:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

